#!/bin/bash
git submodule update --init tools/fff
git submodule update --init tools/googletest
    cd tools/googletest
    git checkout release-1.8.1
    mkdir -p build
    cd build
    cmake ..
    make

