" repoで読み込みたいプラグインのGithubのリポジトリを指定する。
[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

" hookを利用することで、プラグインの読み込みと同時に行いたい処理を設定できる。
[[plugins]]
repo = 'jacoborus/tender.vim'
hook_add = '''
    colorscheme tender
    syntax on
'''
